[package]
name = "vesper"
version = "1.0.0"
authors = ["Berkus Decker <berkus+cargo@metta.systems>"]
description = "Vesper exokernel"
documentation = "https://docs.metta.systems/vesper"
homepage = "https://github.com/metta-systems/vesper"
repository = "https://github.com/metta-systems/vesper"
readme = "README.md"
license = "BSL-1.0"
categories = ["no-std", "embedded", "os"]
publish = false
edition = "2018"

[package.metadata.cargo-xbuild]
memcpy = true

[package.metadata.bootimage]
default-target = "targets/aarch64-vesper-metta.json"

[features]
unstable = []
realtime = []
noserial = []
jlink = [] #'jlink_rtt'

#[lib]
#name = "nucleus"
#path = "src/lib.rs"
#crate-type = ["staticlib"]

[dependencies]
r0 = "0.2.2"
rlibc = "1.0.0"
panic-abort = "0.3.1"
bitflags = "1.0.1"
register = "0.3.2"
cortex-a = "2.4"
#embedded-serial = "0.5.0"
# jlink_rtt = { version = "0.1.0", optional = true }
static_assertions = { version = "0.3.1", features = ["nightly"] }

[profile.dev]
panic = "abort" # @todo try panic_rtt when feature jlink

[profile.release]
panic = "abort"
debug = true
lto = true
# https://github.com/rust-lang/cargo/pull/6564#issuecomment-457971499
incremental = false
