[workspace]
members = [
    "nucleus"
]

[profile.dev]
panic = "abort" # @todo try panic_rtt with feature jlink
opt-level = 's' # otherwise boot code will be mangled

[profile.release]
panic = "abort"
opt-level = 's'
debug = true
lto = true

[profile.test]
opt-level = 's'
debug = true
