[package]
name = "vesper"
version = "0.0.1"
authors = ["Berkus Decker <berkus+cargo@metta.systems>"]
description = "Vesper exokernel"
documentation = "https://docs.metta.systems/vesper"
homepage = "https://github.com/metta-systems/vesper"
repository = "https://github.com/metta-systems/vesper"
readme = "README.md"
license = "BlueOak-1.0.0"
categories = ["no-std", "embedded", "os"]
publish = false
edition = "2018"

[badges]
maintenance = { status = "experimental" }

[features]
# Build for running under QEMU with semihosting, so various halt/reboot options would for example quit QEMU instead.
qemu = ["qemu-exit"]

[dependencies]
r0 = "1.0"
rlibc = "1.0"
qemu-exit = { version = "1.0", optional = true }
cortex-a = { git = "https://github.com/berkus/cortex-a", branch = "feature/add-registers" }
ux = { version = "0.1.3", default-features = false }
usize_conversions = "0.2.0"
bit_field = "0.10.0"
register = "0.5.1"
bitflags = "1.2.1"
